### ISSUE TITLE
Extension use for set alpine startpage when open a new tab 

### ISSUE THREAD

**Issue by 1amSimp1e** [refact0r/alpine#1]
Which extensions do you use to add the website set as new tab? Also, how about customization on Firefox ?

**Comment by refact0r** [comment]
Alpine is packaged as an extension. If you follow the steps in the readme and install the extension it will automatically be set as your new tab page.

What do you mean by customization on firefox?

**Comment by 1amSimp1e** [comment]
i meant if you downloaded, install as you mentioned you cant add the api key for weather and the stock one

**Comment by refact0r** [comment]
I'm sorry if this wasn't clear on the readme, but if you click in the bottom right corner you can open up a config editor where you can put in api keys.

**Comment by 1amSimp1e** [comment]
I works but. Btw, there's anyway i can change the font and have a local backup when i switch to a new machine

**Comment by refact0r** [comment]
No, currently you would have to install Red Hat Mono on every machine. I will add a font setting in the config editor in the next release.
